### PR TITLE
No Trust Verify - service grants

### PR DESCRIPTION
**Pull request by sven-hash**

### CODE REVIEW

**Comment by iamonuwa** [comment]
Hi @sven-hash,

Can you update the template to something unique?

Regards,
Isaac

**Comment by sven-hash** [comment]
Rename the file template.md to ntv_template.md

**Comment by sven-hash** [comment]
> Hi @sven-hash,
> 
> Can you update the template to something unique?
> 
> Regards, Isaac

You mean the name file?

**Comment by iamonuwa** [comment]
Thank you for submitting your application. You will be contacted shortly via email from [grant@nymtech.net](mailto:grant@nymtech.net)

**Pull request merged**
