### PR TITLE
Add polkachu application

### PR DESCRIPTION
**Pull request by PolkachuIntern**

### CODE REVIEW

**Comment by iamonuwa** [comment]
Hi @PolkachuIntern,

Please update the template to something unique

Regards,
Isaac

**Comment by PolkachuIntern** [comment]
Hey, the grants application form we submitted is quite unique. We inserted 45 new lines with unique content. 

Could you please be more specific?

**Comment by iamonuwa** [comment]
Update the name of the file

**Comment by PolkachuIntern** [comment]
Updated. Thanks

**Comment by iamonuwa** [comment]
@PolkachuIntern,

Please remove the `template.md` file to avoid conflict on the main repo.

Thanks,
Isaac.

**Comment by PolkachuIntern** [comment]
Deleted template.md. Thanks!

**Comment by iamonuwa** [comment]
Thank you for submitting your application. You will be contacted shortly via email from grant@nymtech.net

**Comment by PolkachuIntern** [comment]
Thanks 🙏

**Pull request merged**
